-- DELETE_ CÂU LỆNH XÓA DỮ LIỆU

-- CÚ PHÁP 
	-- DELETE FROM table_name WHERE condition;

-- LUU y 
	-- Su dung SELECT INTO de tao ra bang tam thoi truoc khi thuc hanh cau lenh DELETE 


-- TAO RA BANG SINHVIEN_1 TU BANG SINHVIEN (SAO CHEP DU LIEU TU BANG SINHVIEN)
SELECT *
INTO SINHVIEN_1
FROM [dbo].[SinhVien];


-- THEM DU LIEU VAO BANG SINHVIEN_1
INSERT INTO [dbo].[SINHVIEN_1] ([MaSV],[HoTen],[Lop],[Nganh],[DiemTB])
VALUES	('123','HAI','A111','TCNH','8.7'),
		('124','QUOC','A111','TCNH','8.9'),
		('125','VINH','A112','QTKD','9.2');



-- XOA DI 1 SV TRONG BANG SINH VIEN 
DELETE FROM SINHVIEN_1
WHERE [HoTen] LIKE 'VINH';
-- KHI MA RUN CAU LENH NAY THI NO SE XOA DI SINH VIEN TEN 'VINH' CHU KHONG CO XOA DI CAI TABLE NAY

-- KHI TA MUON XOA SACH DU LIEU TRONG BANG DO, NHUNG KHI TA THUC HIEN LENH NAY THI NO CHI XOA HET DU LIEU
-- BANG CHU KHONG XOA DI TABLE
DELETE FROM SINHVIEN_1;

-- CON MUON XOA TABLE SINHVIEN_1 THI TA LAM NHU SAU
DROP TABLE [dbo].[SINHVIEN_1];  



